class Config

  API_BASE_URL = ENV['OST_API_ENDPOINT']
  API_KEY = ENV['OST_API_KEY']
  API_SECRET = ENV['OST_API_SECRET']
  OST_SDK = OSTSdk::Saas::Services.new({api_key: API_KEY, api_secret: API_SECRET, api_base_url: API_BASE_URL})

  USER_ID = ENV['USER_ID']
  CHAIN_ID = ENV['CHAIN_ID']
  DEVICE_ADDRESS = ENV['DEVICE_ADDRESS']
  SESSION_ADDRESS = ENV['SESSION_ADDRESS']
  TRANSACTION_ID = ENV['TRANSACTION_ID']
  RECOVERY_OWNER_ADDRESS = ENV['RECOVERY_OWNER_ADDRESS']


end